biocypher:
  offline: true
  debug: true
  schema_config_path: ./kn/kn_schema.yaml

neo4j:
  database_name: clinical_trials
  delimiter: '\t'
  array_delimiter: "|"
  quote_character: '"'
  skip_duplicate_nodes: true
  skip_bad_relationships: true