biocypher:
  offline: true
  debug: true
  schema_config_path: ./kn_schema.yaml
  strict: false

neo4j:
  database_name: neo4j
  delimiter: '\t'
  array_delimiter: "|"
  quote_character: '"'
  skip_duplicate_nodes: true
  skip_bad_relationships: true

